name: kdbush
description: A very fast static spatial index for 2D points based on a flat KD-tree. A port of javascript kdbush.
version: 0.1.0
homepage: https://github.com/rorystephenson

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
